import type { WorkUnitDefinition } from './types';

export const WORK_UNIT_DEFINITIONS: WorkUnitDefinition[] = [
  {
    id: 'annual-business-plan',
    category: '기획·평가',
    name: '대학발전계획 연계 연간 사업운영 계획',
    dutyTypes: ['정규직'],
    difficulty: 'B',
    period: '매년 3월~4월, 10월',
    approver: '총장',
    regulation: '대학 자체평가 규칙',
    relatedForms: ['대학발전계획 연계 사업운영 자체 평가 및 사업운영계획서'],
    relatedDepartments: ['기획예산팀'],
    keyProcedures: ['협조문 접수', '시설관리위원회 소집', '연간 사업운영 계획 심의', '회의록 및 사업운영계획서 제출'],
    cautions: ['행정부서 및 학부(과) 의견 검토'],
    evidenceHint: '회의록, 사업운영계획서, 협조문',
    performanceMetric: '사업운영계획 수립 및 제출 여부',
  },
  {
    id: 'self-evaluation',
    category: '기획·평가',
    name: '자체평가(중간, 최종)',
    dutyTypes: ['정규직'],
    difficulty: 'B',
    period: '매년 3월~4월, 10월',
    approver: '총장',
    regulation: '대학 자체평가 규칙',
    relatedForms: ['대학발전계획 연계 사업운영 자체 평가 및 사업운영계획서'],
    relatedDepartments: ['기획예산팀'],
    keyProcedures: ['자체평가 요청 접수', '시설관리위원회 소집', '자체평가 심의', '심의 결과 보고'],
    cautions: ['사업운영 결과 요구사항 및 개선 사항 도출', '개선계획 구체화'],
    evidenceHint: '자체평가서, 회의록, 결과보고',
    performanceMetric: '자체평가 및 개선계획 수립 여부',
  },
  {
    id: 'facility-committee',
    category: '기획·평가',
    name: '시설관리위원회 관리',
    dutyTypes: ['정규직'],
    difficulty: 'B',
    period: '사유 발생시',
    approver: '총장',
    regulation: '시설관리위원회 운영규칙',
    relatedForms: ['시설관리위원회 회의록'],
    relatedDepartments: ['기획혁신처'],
    keyProcedures: ['위원회 소집', '회의 개최', '심의', '회의 결과보고'],
    cautions: ['당연직 위원 위촉 기준 확인', '연구실 안전환경관리 및 소방운영계획 심의 사항 확인'],
    evidenceHint: '위원회 소집 공문, 회의록',
    performanceMetric: '위원회 개최 및 심의 건수',
  },
  {
    id: 'regulation-revision',
    category: '기획·평가',
    name: '규정 제정 및 개정',
    dutyTypes: ['정규직'],
    difficulty: 'B',
    period: '사유 발생시',
    approver: '총장',
    regulation: '규정심의위원회 운영규칙',
    relatedForms: ['규정입안서', '관련규정 제정 및 개정(안)'],
    relatedDepartments: ['기획예산팀'],
    keyProcedures: ['규정 내용 검토', '위원회 심의', '심의 요청 발송', '시행 결재 및 공표'],
    cautions: ['관련 위원회 심의 필요', '관련 법령 제정 및 개정 사항 반영'],
    evidenceHint: '규정입안서, 심의 결과 통보, 시행 결재',
    performanceMetric: '규정 제개정 처리 건수',
  },
  {
    id: 'education-facility-status',
    category: '교지·교사관리',
    name: '대학 교육시설 현황 제출',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 116,
    period: '매년 4월, 7월, 10월',
    approver: '총장',
    regulation: '대학설립·운영 규정',
    relatedForms: ['대학재정정보 시스템', '수정요청서'],
    relatedDepartments: ['사학진흥재단', '교육지원팀', '입시지원팀', '학생활동지원팀'],
    keyProcedures: ['교육시설 현황 입력', '관련부서 확인 요청', '집계표 제출', '정보공시 연계자료 확인'],
    cautions: ['교지·교사 인정 범위 확인', '공용면적 포함 입력', '입력 지침서 및 시스템 매뉴얼 참고'],
    evidenceHint: '교육시설 현황 제출 공문, 집계표',
    performanceMetric: '교사확보율 및 교육시설 현황 제출 실적',
  },
  {
    id: 'basic-property',
    category: '교지·교사관리',
    name: '교육용 기본재산 취득 및 처분',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 116,
    period: '사안 발생 시',
    approver: '총장',
    regulation: '고등교육법, 대학설립·운영 규칙',
    relatedForms: ['기본재산 처분(교환) 허가 신청서'],
    relatedDepartments: ['교육부', '사학진흥재단', '법무사', '공인중개사'],
    keyProcedures: ['이사회 승인', '매매계약 또는 처분 신청', '등기 및 재산등재', '처분 결과 보고'],
    cautions: ['취득 재산 공부 확인', '처분 수익금 용도 제한 확인'],
    evidenceHint: '이사회 승인자료, 허가 신청서, 등기자료, 결과보고',
    performanceMetric: '교육용 기본재산 변동 관리 실적',
  },
  {
    id: 'environment-improvement',
    category: '공사관리',
    name: '환경개선 공사',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'A',
    annualHours: 870,
    period: '하계 및 동계방학',
    approver: '총장',
    regulation: '시설관리 운영규칙',
    relatedForms: ['설계도서', '입찰서류', '준공계', '검수서'],
    relatedDepartments: ['총무팀', '해당사업부서'],
    keyProcedures: ['사업공간 확정', '설계', '입찰', '공사시행', '준공 및 검수'],
    cautions: ['법정 정산 항목 확인', '기존 설비 연동 계획 반영', '공사 중 안전 수칙 준수', '개강 1주일 전 완료 목표'],
    evidenceHint: '공사 시행 품의, 입찰자료, 준공계, 검수서',
    performanceMetric: '환경개선공사 시행 건수',
  },
  {
    id: 'facility-maintenance',
    category: '시설관리',
    name: '시설물 유지보수',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 1221,
    period: '사안 발생 시',
    approver: '총장',
    regulation: '시설관리 운영규칙',
    relatedForms: ['발주서', '착공계', '준공계', '검수서'],
    relatedDepartments: ['총무팀', '시공사'],
    keyProcedures: ['원인 파악', '보수 계획 수립', '원가 산출 및 품의', '발주', '준공 및 검수'],
    cautions: ['수업 및 주요 행사 일정 사전 확인', '재발 방지를 위한 장기적 관점의 유지보수'],
    evidenceHint: '현장 사진, 발주서, 검수서, 완료보고',
    performanceMetric: '시설물 유지보수 처리 건수',
  },
  {
    id: 'facility-outsourcing',
    category: '시설관리',
    name: '시설종합관리 위탁용역',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 104,
    period: '매년 1월~2월, 연중',
    approver: '총장',
    regulation: '위탁용역 계약 및 관리 기준',
    relatedForms: ['용역비 산출자료', '계약서', '정산자료'],
    relatedDepartments: ['총무팀', '위탁업체'],
    keyProcedures: ['예산 산출', '입찰', '계약', '운영 관리', '정산'],
    cautions: ['외부 위탁 용역직 관리 및 업무 유대관계 유지'],
    evidenceHint: '계약서, 정산서, 관리일지',
    performanceMetric: '위탁용역 관리 실적',
  },
  {
    id: 'facility-safety-certification',
    category: '안전관리',
    name: '교육시설안전 인증 및 점검',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 109,
    period: '연 2회 점검, 5년 또는 10년마다 인증',
    approver: '총장',
    regulation: '교육시설안전법',
    relatedForms: ['안전점검표', '교육시설통합정보망 자료'],
    relatedDepartments: ['교육부', '한국교육시설안전원'],
    keyProcedures: ['교육시설 안전점검', '안전인증 준비', '통합정보망 입력', '후속조치 관리'],
    cautions: ['안전인증 주기 및 점검 결과 후속조치 확인'],
    evidenceHint: '안전점검표, 인증자료, 통합정보망 입력자료',
    performanceMetric: '교육시설 안전점검 및 인증 실적',
  },
  {
    id: 'education-environment-zone',
    category: '안전관리',
    name: '교육시설 안전성 평가 및 교육환경보호구역 점검',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 109,
    period: '연 2회, 사유 발생 시',
    approver: '총장',
    regulation: '교육시설안전법',
    relatedForms: ['안전성 평가 결과', '순회점검표'],
    relatedDepartments: ['교육지원청', '건설사업자'],
    keyProcedures: ['안전성 평가 실시', '평가 결과 통보', '보호구역 순회점검', '점검표 작성 및 보관'],
    cautions: ['학교 경계 4미터 이내 건설공사 등 평가 대상 확인'],
    evidenceHint: '안전성 평가 결과서, 교육환경보호구역 점검표',
    performanceMetric: '교육환경보호구역 점검 실적',
  },
  {
    id: 'landscape-management',
    category: '시설관리',
    name: '조경관리',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'C',
    annualHours: 94,
    period: '매년 3월~11월',
    approver: '총장',
    regulation: '조경 및 부대시설 관리 기준',
    relatedForms: ['조경작업 보고', '용역자료'],
    relatedDepartments: ['위탁업체'],
    keyProcedures: ['수목 시비', '병충해 방제', '관목 전정', '교목 전정', '잠복소 설치'],
    cautions: ['계절별 작업시기와 수목 상태 확인'],
    evidenceHint: '작업 사진, 용역 결과보고',
    performanceMetric: '조경관리 시행 건수',
  },
  {
    id: 'fire-safety',
    category: '안전관리',
    name: '소방안전관리',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'A',
    annualHours: 945,
    period: '상시',
    approver: '총장',
    regulation: '화재의 예방 및 안전관리에 관한 법률, 소방시설 설치 및 관리에 관한 법률',
    relatedForms: ['소방점검 결과보고', '소방훈련 결과보고'],
    relatedDepartments: ['소방서', '소방점검업체'],
    keyProcedures: ['종합정밀점검', '작동기능점검', '소방훈련 및 교육', '위험물 관리 실태조사'],
    cautions: ['법정 점검 주기 및 후속조치 이행 관리'],
    evidenceHint: '점검표, 훈련 결과보고, 후속조치 자료',
    performanceMetric: '소방안전 실무 훈련 및 점검 횟수',
  },
  {
    id: 'electric-safety',
    category: '안전관리',
    name: '전기안전관리',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'A',
    annualHours: 945,
    period: '상시',
    approver: '총장',
    regulation: '전기안전관리 관련 법령',
    relatedForms: ['전기설비 점검표', '열화상 측정 결과'],
    relatedDepartments: ['전기안전관리자', '전기점검업체'],
    keyProcedures: ['누설전류 측정', '고압설비 열화상 촬영', '비상발전기 무부하 운전', '전기설비 법정검사'],
    cautions: ['비상발전기 및 태양광 설비 위치 확인'],
    evidenceHint: '점검표, 측정 결과, 법정검사 자료',
    performanceMetric: '전기안전 점검 및 후속조치 실적',
  },
  {
    id: 'laboratory-safety',
    category: '안전관리',
    name: '연구실안전관리',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'A',
    annualHours: 945,
    period: '상시',
    approver: '총장',
    regulation: '연구실 안전 관련 법령 및 연구실 안전관리규칙',
    relatedForms: ['연구실 안전교육 이수현황', '정기점검 및 정밀안전진단 결과'],
    relatedDepartments: ['학부(과)', '연구실책임자', '안전진단업체'],
    keyProcedures: ['연구실 안전교육', '실태조사 등록', '현장점검', '정기점검 및 정밀안전진단', '특수건강검진'],
    cautions: ['미이수자 독려 및 후속조치 이행 관리'],
    evidenceHint: '교육 이수현황, 점검 결과보고, 후속조치 자료',
    performanceMetric: '2등급 이상 실험실습실 수 및 안전교육 이수율',
  },
  {
    id: 'other-safety',
    category: '안전관리',
    name: '기타 안전관리(승강기, 가스, 기계)',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 945,
    period: '상시',
    approver: '총장',
    regulation: '승강기·가스·기계설비 안전관리 관련 법령',
    relatedForms: ['승강기 점검표', '가스설비 점검표', '기계설비 성능점검 결과'],
    relatedDepartments: ['승강기 업체', '가스 점검업체', '기계설비 점검업체'],
    keyProcedures: ['승강기 안전점검', '가스설비 안전점검', '도시가스 정압기 점검', '기계설비 성능점검'],
    cautions: ['비상상황 시 임의조작 금지 및 전문업체 연계'],
    evidenceHint: '안전점검표, 성능점검 결과보고',
    performanceMetric: '기타 안전관리 점검 실적',
  },
  {
    id: 'general-management',
    category: '일반관리',
    name: '일반관리',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'C',
    period: '상시',
    approver: '총장',
    regulation: '일반 행정 관리 기준',
    relatedForms: ['업무일지', '보고자료'],
    relatedDepartments: ['관련부서'],
    keyProcedures: ['일반 행정 처리', '자료 작성', '보고 및 보관'],
    cautions: ['반복 업무 누락 방지'],
    evidenceHint: '업무일지, 보고자료',
    performanceMetric: '일반관리 처리 건수',
  },
  {
    id: 'outsourcing-management',
    category: '시설관리',
    name: '위탁관리',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    period: '상시',
    approver: '총장',
    regulation: '위탁관리 계약 기준',
    relatedForms: ['정산서', '계약서'],
    relatedDepartments: ['위탁업체'],
    keyProcedures: ['위탁관리비 정산', '폐기물·폐수·정화조·방역 등 위탁 관리'],
    cautions: ['계약기간 및 정산 누락 확인'],
    evidenceHint: '정산서, 위탁관리 자료',
    performanceMetric: '위탁관리 정산 및 점검 실적',
  },
  {
    id: 'facility-support',
    category: '시설관리',
    name: '시설관리',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 1221,
    period: '상시',
    approver: '총장',
    regulation: '시설관리 운영규칙',
    relatedForms: ['구입 품의', '청소 및 수질검사 자료'],
    relatedDepartments: ['관련부서', '위탁업체'],
    keyProcedures: ['건물관리용품 구입', '정화조 청소', '저수조 청소', '수질검사'],
    cautions: ['시설별 주기 관리 및 결과자료 보관'],
    evidenceHint: '품의서, 검사 결과, 청소 결과보고',
    performanceMetric: '시설관리 정기 업무 처리 건수',
  },
  {
    id: 'asset-inventory',
    category: '자산관리',
    name: '자산 재물조사',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 739,
    period: '매년 6월~9월',
    approver: '총장',
    regulation: '기자재 및 비품관리 규칙',
    relatedForms: ['재물조사 결과보고'],
    relatedDepartments: ['학부(과)', '행정부서'],
    keyProcedures: ['재물조사 준비', '부서별 결과 취합', '현장조사', '결과보고서 작성'],
    cautions: ['자산번호, 위치, 상태 확인 및 e자산관리 시스템 반영'],
    evidenceHint: '재물조사표, 결과보고서',
    performanceMetric: '재물조사 완료율 및 자산 현행화 실적',
  },
  {
    id: 'asset-disposal',
    category: '자산관리',
    name: '자산 불용처분',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 739,
    period: '매년 9월~2월',
    approver: '총장',
    regulation: '기자재 및 비품관리 규칙',
    relatedForms: ['불용신청서', '불용처분 결과보고'],
    relatedDepartments: ['학부(과)', '행정부서', '폐기업체'],
    keyProcedures: ['불용신청서 취합', '위원회 회의', '법인 승인 제청', '입찰 및 폐기업체 선정', '처분 결과보고'],
    cautions: ['절차적 요건 및 위원회 운영 기준 확인'],
    evidenceHint: '불용신청서, 회의록, 처분 결과보고',
    performanceMetric: '불용처분 처리 건수',
  },
  {
    id: 'insurance-management',
    category: '자산관리',
    name: '보험가입',
    dutyTypes: ['정규직'],
    difficulty: 'B',
    annualHours: 190,
    period: '매년 3월~2월',
    approver: '총장',
    regulation: '보험가입 및 위험관리 기준',
    relatedForms: ['보험가입 증권', '정산자료'],
    relatedDepartments: ['보험사', '재무팀'],
    keyProcedures: ['학교경영자배상책임보험', '연구활동종사자 상해보험', '차량보험', '가스·승강기·화재보험 관리'],
    cautions: ['보험기간과 보장 대상 누락 확인'],
    evidenceHint: '보험증권, 가입내역, 정산자료',
    performanceMetric: '보험가입 및 갱신 완료 실적',
  },
  {
    id: 'education-facility-fee',
    category: '자산관리',
    name: '한국교육시설안전원 회비납부',
    dutyTypes: ['정규직'],
    difficulty: 'C',
    annualHours: 190,
    period: '매년 12월~3월',
    approver: '총장',
    regulation: '한국교육시설안전원 회비 납부 기준',
    relatedForms: ['건물 및 부속물 현황', '회비 납부자료'],
    relatedDepartments: ['한국교육시설안전원', '재무팀'],
    keyProcedures: ['건물 현황 현행화', '가입 공문 발송', '납부금액 확정', '정기가입 회비납부'],
    cautions: ['건물 및 부속물 현황 최신화'],
    evidenceHint: '가입 공문, 납부 영수증',
    performanceMetric: '회비 납부 완료 여부',
  },
  {
    id: 'tax-payment',
    category: '자산관리',
    name: '세금 납부',
    dutyTypes: ['정규직'],
    difficulty: 'C',
    annualHours: 190,
    period: '매년 3월~2월',
    approver: '총장',
    regulation: '건물 및 재산 세금납부',
    relatedForms: ['납부서', '결재문서'],
    relatedDepartments: ['재무팀', '지방자치단체'],
    keyProcedures: ['자동차세 납부', '상업시설 재산세 납부', '연수원 토지 재산세 및 종합부동산세 납부'],
    cautions: ['납부기한 및 과세 대상 확인'],
    evidenceHint: '납부서, 영수증, 결재문서',
    performanceMetric: '세금 납부 기한 준수 여부',
  },
  {
    id: 'rental-fee-billing',
    category: '임대시설 관리 및 대관',
    name: '교내 임대업체 임대료 청구',
    dutyTypes: ['정규직'],
    difficulty: 'B',
    annualHours: 176,
    period: '매년 3월~2월',
    approver: '팀장',
    regulation: '임대시설 관리 운영 기준',
    relatedForms: ['월별 검침일지', '납부청구서'],
    relatedDepartments: ['재무팀', '임대업체'],
    keyProcedures: ['검침일지 작성', '임대료·관리비 계산', '청구현황 작성', '팀장결재 및 재무팀 제출'],
    cautions: ['검침자료와 청구금액 대조'],
    evidenceHint: '검침일지, 청구서, 결재문서',
    performanceMetric: '임대료 청구 및 수납 관리 실적',
  },
  {
    id: 'campus-asset-work',
    category: '자산관리',
    name: '교내 자산관련 업무',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 739,
    period: '매년 3월~2월',
    approver: '총장',
    regulation: '기자재 및 비품관리 규칙',
    relatedForms: ['자산등재 자료', '자산이관 자료', '자산라벨'],
    relatedDepartments: ['학부(과)', '행정부서'],
    keyProcedures: ['자산등재', '자산이관', '자산라벨 발행', '수증물품 등록', '교원 연구실 이전 지원'],
    cautions: ['e서비스 자산현황 정보 수정 및 라벨 부착 확인'],
    evidenceHint: '자산등재 자료, 이관 신청서, 라벨 발행 기록',
    performanceMetric: '자산 현행화 및 이관 처리 건수',
  },
  {
    id: 'finance-closing-support',
    category: '자산관리',
    name: '재무팀 결산 협조',
    dutyTypes: ['정규직'],
    difficulty: 'B',
    annualHours: 739,
    period: '매년 2월',
    approver: '관련규정',
    regulation: '결산 협조 기준',
    relatedForms: ['결산자료', '자산등재 완료자료'],
    relatedDepartments: ['재무팀'],
    keyProcedures: ['e서비스 자산등재 완료', '기자재·비품·차량·건물 결산 자료 작성', '자료 검토 및 수정', '최종확정'],
    cautions: ['결산 기준일과 자산등재 누락 확인'],
    evidenceHint: '결산자료, 검토 결과',
    performanceMetric: '결산자료 제출 완료 여부',
  },
  {
    id: 'copy-room-settlement',
    category: '임대시설 관리 및 대관',
    name: '구내 복사실 이용금액 정산',
    dutyTypes: ['정규직'],
    difficulty: 'C',
    period: '매년 3월~2월',
    approver: '총장',
    regulation: '구내 복사실 정산 기준',
    relatedForms: ['복사신청서', '세금계산서', '이용현황'],
    relatedDepartments: ['구내복사실', '재무팀'],
    keyProcedures: ['복사신청서 접수', '청구서 및 세금계산서 요청', '이용현황 작성', '내부결재 및 지출'],
    cautions: ['신청서와 청구서 금액 대조'],
    evidenceHint: '신청서, 청구서, 지출 결재',
    performanceMetric: '복사실 이용금액 정산 실적',
  },
  {
    id: 'lab-equipment-maintenance',
    category: '기술지원',
    name: '실험실습기자재 유지 보수',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 1304,
    period: '매년 3월~다음해 2월, 사유발생시',
    approver: '총장',
    regulation: '실험실습기자재 유지보수 기준',
    relatedForms: ['기자재 수리 신청', '교정 신청', '정산자료'],
    relatedDepartments: ['학부(과)', '제조사', '유지보수업체'],
    keyProcedures: ['수리 및 교정 신청 접수', '장애 확인', '부품 구입 또는 제조사 의뢰', '수리비 정산'],
    cautions: ['기본 운용방법 및 사용자 정비 지침 확인'],
    evidenceHint: '수리 신청서, 사진, 정산자료',
    performanceMetric: '실험실습기자재 유지보수 처리 건수',
  },
  {
    id: 'classroom-multimedia',
    category: '기술지원',
    name: '일반강의실 멀티미디어 시스템 운영',
    dutyTypes: ['정규직', '계약직'],
    difficulty: 'B',
    annualHours: 1304,
    period: '매년 7월~8월, 다음해 1~2월',
    approver: '관련규정',
    regulation: '강의실 멀티미디어 시스템 운영 기준',
    relatedForms: ['점검표', '장애처리 내역'],
    relatedDepartments: ['학부(과)', '정보전산 관련부서'],
    keyProcedures: ['개강 전 점검', '전자교탁 운영', '영상·음향 장비 점검', '장애 처리'],
    cautions: ['PC, 전산, 네트워크, 영상·음향 장비 기본 상태 확인'],
    evidenceHint: '점검표, 장애처리 내역, 사진',
    performanceMetric: '강의실 멀티미디어 점검 및 장애처리 건수',
  },
];

export const getWorkUnitById = (id: string) =>
  WORK_UNIT_DEFINITIONS.find((unit) => unit.id === id);

export const WORK_UNIT_CATEGORIES = Array.from(
  new Set(WORK_UNIT_DEFINITIONS.map((unit) => unit.category)),
);

